[package]
name = "hello_nats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = "0.29.0"
futures = "0.3.28"
tokio = { version = "1.29.1", features = ["rt", "rt-multi-thread", "macros"] }
