on: workflow_dispatch
jobs:
  nats:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          mkdir -p tmp/bin && cd $_
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          mv nats-server nats-server.exe
          cygpath -w "$(pwd)" | tee -a "$GITHUB_PATH"
      - run: nats-server -v