name: nats

on: workflow_dispatch
#on: push

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        config:
          #- os: ubuntu-latest-4-cores
          #- os: windows-latest
          - os: ubuntu-latest
          #- os: macos-latest

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: tools linux
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          curl -L -o nats-server.tar.gz https://github.com/nats-io/nats-server/releases/download/v2.9.17/nats-server-v2.9.17-linux-amd64.tar.gz
          mkdir tools-nats-server
          tar -xf nats-server.tar.gz -C tools-nats-server --strip-components=1
          echo "$(pwd)/tools-nats-server" >> $GITHUB_PATH

      - name: tools macos
        if: ${{ matrix.config.os == 'macos-latest' }}
        run: |
          curl -L -o nats-server.tar.gz https://github.com/nats-io/nats-server/releases/download/v2.9.17/nats-server-v2.9.17-darwin-amd64.tar.gz
          mkdir tools-nats-server
          tar -xf nats-server.tar.gz -C tools-nats-server --strip-components=1
          echo "$(pwd)/tools-nats-server" >> $GITHUB_PATH
        
      - name: tools windows
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          Invoke-WebRequest https://github.com/nats-io/nats-server/releases/download/v2.9.17/nats-server-v2.9.17-windows-amd64.zip -OutFile tools-nats-server.zip
          Expand-Archive tools-nats-server.zip
          $current_path = (Get-Item .).FullName
          echo "$current_path\tools-nats-server\nats-server-v2.9.17-windows-amd64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: nats-server
        run: nats-server -v
      
      - name: build
        run:  dotnet build --p:WarningLevel=0
        
      - name: test
        run: dotnet test --no-build --logger:"console;verbosity=detailed" nats/nats.net.v2/tests/NATS.Client.Core.Tests
