on: workflow_dispatch
jobs:
  nats:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@dev | PREFIX=. sh
          mv nats-server nats-server.exe
      - run: nats-server -v