name: nats3
on: workflow_dispatch
jobs:

  ubuntu_build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - branch: dev
          #- branch: main 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          
      - name: tools
        run: |
          mkdir tools
          cd tools
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@${{ matrix.config.branch }} | PREFIX=. sh
          echo "$(pwd)" | tee -a "$GITHUB_PATH"
          
      - name: nats-server version
        run: nats-server -v
        
      - name: build
        run: dotnet build --p:WarningLevel=0
        
      - name: test
        run: dotnet test --no-build --logger:"console;verbosity=normal" nats/nats.net.v2/tests/NATS.Client.Core.Tests
