name: nats2
on: workflow_dispatch
jobs:

  ubuntu_build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - branch: dev
          - branch: main 
    runs-on: ubuntu-latest
    steps:
      - name: tools
        run: |
          mkdir tools-nats-server
          cd tools-nats-server
          curl -Ls 'https://binaries.nats.dev/binary/github.com/nats-io/nats-server/v2?os=linux&arch=amd64&version=${{ matrix.config.branch }}' -o nats-server
          chmod +x nats-server
          echo "$(pwd)/tools-nats-server" >> $GITHUB_PATH
      - name: chk
        run: |
          echo _____uname
          uname -a
          echo _____PATH
          echo $PATH
          echo _____ls -la
          ls -la
          echo _____ls -ld
          ls -ld "$(pwd)/tools-nats-server"
          echo _____ls -l
          ls -l "$(pwd)/tools-nats-server"
          echo _____file
          file "$(pwd)/tools-nats-server/nats-server"
      - name: nats-server
        run: |
          "$(pwd)/tools-nats-server/nats-server" -v
        #run: nats-server -v
        
#          curl -Ls 'https://binaries.nats.dev/binary/github.com/nats-io/nats-server/v2?os=windows&arch=amd64&version=dev' -o nats-server.exe